### ISSUE TITLE
Provider autocomplete not encoding request correctly

### ISSUE THREAD

**Issue by SamJamCul** [DFE-Digital/publish-teacher-training#1025]
Publish uses the provider autocomplete feature for assigning an accredited provider to a course.

Users can potentially copy and paste unicode characters into the provider field resulting in this lovely error
https://sentry.io/organizations/dfe-bat/issues/1610835288/?project=1407453&referrer=slack

Find Teacher Training has implemented a fix for this already

https://github.com/DFE-Digital/find-teacher-training/blob/master/app/webpacker/scripts/autocomplete.js#L11

## Todo
- [ ] Encode the provider query (unicode to utf-8)
- [ ] Test for appropriate encoding
- [ ] Similar test to find if possible

**Comment by SamJamCul** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[S] Publish provider autocomplete not encoding request correctly](https://trello.com/c/4nSbRPzG/3276-s-publish-provider-autocomplete-not-encoding-request-correctly)
